### ISSUE TITLE
Update `kup` cheat-sheet

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/gitbook-kontrol#26]
The `kup` [cheat-sheet](https://docs.runtimeverification.com/kontrol/cheatsheets/kup-cheatsheet) needs to be updated to reflect the changes in `kup-v0.2.x`, see `kup`'s [CHANGELOG](https://github.com/runtimeverification/kup/blob/master/CHANGELOG). 

Items to add:

- [x] Allow arbitrary overrides of the form `kup install ... --override ... github:...`
- [x] Removed `kup update` as it was functionally equivalent to `kup install`
- [x] Renamed `kup remove` to `kup uninstall` so as to make it clear its associated with the `kup install` operation and not the `kup add`
- [x] Added `kup publish` which allows uploading a package to a cachix cache and pinning it to it's URI (not sure if this is useful for general users. @geo2a please advise)
- [ ] Added the ability to query the `k-framework-binary.cachix.org` cache to download pre-built binaries of a package if they exist in the pinned cache (same concern as with the last item)

**Comment by JuanCoRo** [comment]
I've added the list of items to the top comment.

**Comment by geo2a** [comment]
`kup publish` is not useful for general users, no.

**Comment by reekamaharaj** [comment]
@JuanCoRo The three checkboxes left here, are those edits I still need to make? If so I will need some clarification on what I should do to address them. Otherwise I think this can be closed.

**Comment by reekamaharaj** [comment]
Closing this issue after talking with Gerogy. The kup cheatsheet table has now been updated with all the commands that will show up when you run `kup --help`
