### ISSUE TITLE
Explain `forge init --no-git` nuances

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/gitbook-kontrol#3]
The suggested way to create the kevm-foundry integration example foundry project is with this command:
https://github.com/runtimeverification/gitbook-kontrol/blob/ec08f9d4da0fff251a64446f7513c3dbdeb65452/kevm-foundry-integration-example/README.md?plain=1#L10
This is nice since it avoids creating a git repo that won't be used probably. However, there seems to be some nuances when the foudry project is not a git repository. Namely, the `forge build` and `forge test` commands don't work outside of the repo's root. Instead of the usual output, it only outputs `Nothing to compile` in both commands
```bash
➜  kevmexample forge build
[⠒] Compiling...
No files changed, compilation skipped
➜  kevmexample forge test
[⠒] Compiling...
No files changed, compilation skipped

Running 2 tests for test/Counter.t.sol:CounterTest
[PASS] testIncrement() (gas: 28346)
[PASS] testSetNumber(uint256,bool) (runs: 256, μ: 27785, ~: 28641)
Test result: ok. 2 passed; 0 failed; finished in 8.09ms
➜  kevmexample cd src 
➜  src forge build
Nothing to compile
➜  src forge test
Nothing to compile
➜  src cd ../test 
➜  test forge build
Nothing to compile
➜  test forge test
Nothing to compile
```
I believe we should document this somehow or drop the `--no-git` flag.

Moreover, using `forge init --no-git` makes the  following sentence incorrect:
https://github.com/runtimeverification/gitbook-kontrol/blob/ec08f9d4da0fff251a64446f7513c3dbdeb65452/kevm-foundry-integration-example/property-verification-using-kevm.md?plain=1#L40

**Comment by reekamaharaj** [comment]
I have gone ahead and removed `--no-git` because it doesn't seem like it needs to be there. @anvacaru If you disagree I can add a note to mention that `--no-git` flag is available. However, that is something a reader can look up on the foundry docs if they really want to not have git involved.
