### ISSUE TITLE
Updates & pointers to Kontrol documentation

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/gitbook-kontrol#7]
We should make this documentation (https://docs.runtimeverification.com/kontrol) the source of truth for using Kontrol to verify Foundry tests and
- [x] Transfer all the information missing in the documentation from [foundry-demo](https://github.com/runtimeverification/foundry-demo)
- [x] Add other up-to-date instructions for using Kontrol
- [x] Link to the docs from [foundry-demo](https://github.com/runtimeverification/foundry-demo)
- [x] Make sure people know they should file issues/updates to documentation in this repo: https://github.com/runtimeverification/gitbook-kontrol
- [x] Pin the link to this Kontrol documentation to our Discord channel (our Telegram channel seems to be used mostly for announcements, so we can probably skip it for now if it's still the case — https://t.me/rv_inc/32)

We might also consider archiving the [foundry-demo](https://github.com/runtimeverification/foundry-demo) repo, but I've realized we might want to have a repository that's easy to clone and run Kontrol on, i.e., that contains files such as `lemmas.k` and `KEVMCheats.sol`.

**Comment by reekamaharaj** [comment]
On the [Foundry-demo](https://github.com/runtimeverification/foundry-demo) Readme it goes over the contents of the repository. Should that info go on to the Gitbook, and if so how would you like to include that?

If the Foundry-demo repo will continue to live then I'd suggest excluding that from the Gitbook. Main concern is that it will be forgotten and not updated as it is needed, where as a demo that is actively used wouldn't likely be forgotten.

However, if the repo is planned to be archived then we should definitely make sure that info lives on the Gitbook. We can always make a section on the gitbook to include the file contents of lemmas.k and KEVMCheats.sol. 

We will just want to make sure that theres something in place to make sure nothing becomes depreciated.

**Comment by reekamaharaj** [comment]
- KEVMCheatsheet.sol code link in Gitbook needs to be changed to kontrol repo link
